### ISSUE TITLE
Ollama?

### ISSUE THREAD

**Issue by qwaszaq** [chrisammon3000/dspy-neo4j-knowledge-graph#1]
I’d like to keep it local as much as possible and I just wonder if it is possible to let it rock on Ollama?

**Comment by chrisammon3000** [comment]
@qwaszaq Yes, absolutely but you will need to write your own integration at the moment since it is just using OpenAI.

**Comment by peterbull** [comment]
I've got it up and running with Ollama with a small change. In `run.py` change:

```python
lm = dspy.OpenAI(
    model="gpt-4",
    max_tokens=1024,
)
```
To this:
```python
lm = dspy.OllamaLocal(
    "open-hermes-2-4_0", 
    max_tokens=3000, 
    model_type="chat")
```
Just drop in the name of your model at `open-hermes-2-4_0` and make sure that Ollama is running at http://localhost:11434/.

**Comment by creer** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lukaszhanusik, @simoneromanotoptal, @nschlemm, @DammianMiller, @divijgupta, @kyegomez, @chronosoracle, @sthimm, @iamawanishmaurya, @diegocaumont, @amlcodes, @0xtito, @helhindi, @vasnt, @valtab, @acmayberry, @S0AndS0, @jadedgnome, @unconst, @nravic, @TheFloatingString, @ktm1312, @Cxxshyy, @thomasczer, @annakaz, @DailySuicide, @ndubuisx, @lan956, @worthmining, @HusseinLezzaik, @sparoj1377, @Nordicus7060, @justheuristic, @Cam-B, @astanziola, @shittao1000, @shariq, @dendisuhubdy, @chillios-dev, @loicteillard, @KNipunDananjaya, @Aniu77, @ccyanxyz, @8gratitude8, @hiroki-tei, @ImKelp, @stereoplegic, @bansal19, @degencodebeast, @sebastienrousseau
